    shared.gloveHits = {
    
    ["Default"] = game.ReplicatedStorage:FindFirstChild("b"),
    ["Extended"] = game.ReplicatedStorage:FindFirstChild("b"),
    
    ----------------------------------------
     
    ["T H I C K"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Squid"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Gummy"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["RNG"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Tycoon"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Charge"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Baller"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Tableflip"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Booster"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Shield"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Track"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Goofy"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Confusion"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Elude"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Glitch"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Snowball"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["🗿"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Obby"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Voodoo"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Leash"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Flamarang"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Kinetic"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Berserk"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Rattlebones"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Chain"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Ping Pong"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Psycho"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Kraken"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Counter"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Hammer"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Excavator"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Slicer"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Whirlwind"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ["Home Run"] = game.ReplicatedStorage:FindFirstChild("GeneralHit"),
    ----------------------------------------
    
    ["Diamond"] = game.ReplicatedStorage:FindFirstChild("DiamondHit"),
    ["ZZZZZZZ"] = game.ReplicatedStorage:FindFirstChild("ZZZZZZZHit"),
    ["Brick"] = game.ReplicatedStorage:FindFirstChild("BrickHit"),
    ["Snow"] = game.ReplicatedStorage:FindFirstChild("SnowHit"),
    ["Pull"] = game.ReplicatedStorage:FindFirstChild("PullHit"),
    ["Flash"] = game.ReplicatedStorage:FindFirstChild("FlashHit"),
    ["Spring"] = game.ReplicatedStorage:FindFirstChild("springhit"),
    ["Swapper"] = game.ReplicatedStorage:FindFirstChild("HitSwapper"),
    ["Bull"] = game.ReplicatedStorage:FindFirstChild("BullHit"),
    ["Dice"] = game.ReplicatedStorage:FindFirstChild("DiceHit"),
    ["Ghost"] = game.ReplicatedStorage:FindFirstChild("GhostHit"),
    ["Thanos"] = game.ReplicatedStorage:FindFirstChild("ThanosHit"),
    ["Stun"] = game.ReplicatedStorage:FindFirstChild("HtStun"),
    ["Za Hando"] = game.ReplicatedStorage:FindFirstChild("zhramt"),
    ["Fort"] = game.ReplicatedStorage:FindFirstChild("Fort"),
    ["Magnet"] = game.ReplicatedStorage:FindFirstChild("MagnetHIT"),
    ["Pusher"] = game.ReplicatedStorage:FindFirstChild("PusherHit"),
    ["Anchor"] = game.ReplicatedStorage:FindFirstChild("hitAnchor"),
    ["Space"] = game.ReplicatedStorage:FindFirstChild("HtSpace"),
    ["Boomerang"] = game.ReplicatedStorage:FindFirstChild("BoomerangH"),
    ["Dream"] = game.ReplicatedStorage:FindFirstChild("Dreamhit"),
    ["Mail"] = game.ReplicatedStorage:FindFirstChild("MailHit"),
    ["Golden"] = game.ReplicatedStorage:FindFirstChild("GoldenHit"),
    ["Cheeky"] = game.ReplicatedStorage:FindFirstChild("CheekyHit"),
    ["Reaper"] = game.ReplicatedStorage:FindFirstChild("ReaperHit"),
    ["Defense"] = game.ReplicatedStorage:FindFirstChild("DefenseHit"),
    ["Killstreak"] = game.ReplicatedStorage:FindFirstChild("KSHit"),
    ["Reverse"] = game.ReplicatedStorage:FindFirstChild("ReverseHit"),
    ["Shukuchi"] = game.ReplicatedStorage:FindFirstChild("ShukuchiHit"),
    ["Duelist"] = game.ReplicatedStorage:FindFirstChild("DuelistHit"),
    ["Woah"] = game.ReplicatedStorage:FindFirstChild("woahHit"),
    ["Ice"] = game.ReplicatedStorage:FindFirstChild("IceHit"),
    ["Adios"] = game.ReplicatedStorage:FindFirstChild("hitAdios"),
    ["Blocked"] = game.ReplicatedStorage:FindFirstChild("BlockedHit"),
    ["Engineer"] = game.ReplicatedStorage:FindFirstChild("engiehit"),
    ["Rocky"] = game.ReplicatedStorage:FindFirstChild("RockyHit"),
    ["Conveyor"] = game.ReplicatedStorage:FindFirstChild("ConvHit"),
    ["STOP"] = game.ReplicatedStorage:FindFirstChild("STOP"),
    ["Phantom"] = game.ReplicatedStorage:FindFirstChild("PhantomHit"),
    ["Wormhole"] = game.ReplicatedStorage:FindFirstChild("WormHit"),
    ["Acrobat"] = game.ReplicatedStorage:FindFirstChild("AcHit"),
    ["Plague"] = game.ReplicatedStorage:FindFirstChild("PlagueHit"),
    ["Megarock"] = game.ReplicatedStorage:FindFirstChild("DiamondHit"),
    ["[REDACTED]"] = game.ReplicatedStorage:FindFirstChild("ReHit"),
    ["bus"] = game.ReplicatedStorage:FindFirstChild("hitbus"),
    ["Phase"] = game.ReplicatedStorage:FindFirstChild("PhaseH"),
    ["Warp"] = game.ReplicatedStorage:FindFirstChild("WarpHt"),
    ["Bomb"] = game.ReplicatedStorage:FindFirstChild("BombHit"),
    ["Bubble"] = game.ReplicatedStorage:FindFirstChild("BubbleHit"),
    ["Jet"] = game.ReplicatedStorage:FindFirstChild("JetHit"),
    ["Shard"] = game.ReplicatedStorage:FindFirstChild("ShardHIT"),
    ["potato"] = game.ReplicatedStorage:FindFirstChild("potatohit"),
    ["Cult"] = game.ReplicatedStorage:FindFirstChild("CULTHit"),
    ["bob"] = game.ReplicatedStorage:FindFirstChild("bobhit"),
    ["buddies"] = game.ReplicatedStorage:FindFirstChild("buddiesHIT"),
    ["Moon"] = game.ReplicatedStorage:FindFirstChild("CelestialHit"),
    ["Jupiter"] = game.ReplicatedStorage:FindFirstChild("CelestialHit"),
    ["Spy"] = game.ReplicatedStorage:FindFirstChild("SpyHit"),
    ["Detonator"] = game.ReplicatedStorage:FindFirstChild("DetonatorHit"),
    ["Rage"] = game.ReplicatedStorage:FindFirstChild("GRRRR"),
    ["Trap"] = game.ReplicatedStorage:FindFirstChild("traphi"),
    ["Orbit"] = game.ReplicatedStorage:FindFirstChild("Orbihit"),
    ["Hybrid"] = game.ReplicatedStorage:FindFirstChild("HybridCLAP"),
    ["Slapple"] = game.ReplicatedStorage:FindFirstChild("SlappleHit"),
    ["Disarm"] = game.ReplicatedStorage:FindFirstChild("DisarmH"),
    ["Dominance"] = game.ReplicatedStorage:FindFirstChild("DominanceHit"),
    ["rob"] = game.ReplicatedStorage:FindFirstChild("robhit"),
    ["Link"] = game.ReplicatedStorage:FindFirstChild("LinkHit"),
    ["Rhythm"] = game.ReplicatedStorage:FindFirstChild("rhythmhit"),
    ["Hitman"] = game.ReplicatedStorage:FindFirstChild("HitmanHit"),
    ["Rojo"] = game.ReplicatedStorage:FindFirstChild("RojoHit"),
    ["Thor"] = game.ReplicatedStorage:FindFirstChild("ThorHit"),
    ["Custom"] = game.ReplicatedStorage:FindFirstChild("CustomHit"),

    
    ----------------------------------------
    
    ["Mitten"] = game.ReplicatedStorage:FindFirstChild("MittenHit"),
    ["Hallow Jack"] = game.ReplicatedStorage:FindFirstChild("HallowHIT"),

    ----------------------------------------

    ["Boogie"] = game.ReplicatedStorage:FindFirstChild("HtStun"),
    ["Balloony"] = game.ReplicatedStorage:FindFirstChild("HtStun"),

    ----------------------------------------
    
    ["OVERKILL"] = game.ReplicatedStorage:FindFirstChild("Overkillhit"),
    ["The Flex"] = game.ReplicatedStorage:FindFirstChild("FlexHit"),
    ["God's Hand"] = game.ReplicatedStorage:FindFirstChild("Godshand"),
    ["Error"] = game.ReplicatedStorage:FindFirstChild("Errorhit")
    
}
